### ISSUE TITLE
Logo file doesn't show on Exhibit Summary Page

### ISSUE THREAD

**Issue by jcmundy** [omeka/theme-bigpicture#24]
The logo file is showing on all other pages, but the text title/link shows on exhibit summary pages.

**Comment by kimisgold** [comment]
Would it be possible to provide a live example? I've been able to set a logo file and see it on my exhibit summary page.

**Comment by jcmundy** [comment]
This is the site: https://ornamentinflux.collections.carlos.emory.edu/ but the exhibits are not set to public yet.

**Comment by kimisgold** [comment]
That makes this a little tricky to troubleshoot. What plugins do you have installed?

**Comment by jcmundy** [comment]
Here is an example that is now live: https://ornamentinflux.collections.carlos.emory.edu/exhibits/show/ornamentinflux

**Comment by kimisgold** [comment]
I'm still having trouble finding something within the theme itself that might be an issue. One idea though: do you have the exhibit theme manually set to "Big Picture"? If it's set to "Big Picture" instead of "Currently Selected Theme", it's possible to have exhibit theme configuration settings different from your site theme configuration settings. If for some reason you need different settings for your exhibits, that's fine: just make sure to reassign your logo file within the exhibit theme settings.

Having your exhibit theme set to "Currently Selected Theme" will automatically inherit the site's theme settings.

**Comment by jcmundy** [comment]
Thank you!  That was the error.
