### ISSUE TITLE
Testing: Video support in item/show galleries

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-bigpicture#27]
This feature has already been included in the latest release, but I wanted to get more eyes on it before it gets pulled into Omeka.net. Please test the following:

* Videos attached to items appear in the gallery and can play both as the only files and as part of a mixed set of file types.
* Subtitle files can be attached and work properly.
  * They should not appear in the "Other Files" listing.
  * Track and video files must all share the same base file name (ex: "video.mp4", "video.vtt")
  * Theme now supports the following values for track metadata:
        * Dublin Core: Type ("subtitles", "captions", etc)
        * Dublin Core: Language (the language code for the track)
        * Dublin Core: Title (the label for the track)
  * Multiple language tracks are supported. They still must share the same base file name as the video: the user differentiates between them using their Dublin Core metadata.

This feature is on the `master` branch and should be tested on all major browsers for both desktop and mobile devices.

**Comment by katknow** [comment]
The video plays perfectly fine, and subtitles do not appear as other files. However, the English subtitles only play if I’m logged in on Firefox, Chrome, and Edge and the options do not show for French and Spanish at all until you navigate to the public page while logged in. All subtitle options do appear in menu on video on public page even though they do not work if not logged in. Tried clearing cache but still didn’t work to fix. All of the subtitles do work when using Safari. (I didn't screen shot for every theme but the issue is the same across so including screenshots on The Daily theme).

**Comment by kimisgold** [comment]
@katknow Hmm, I'm having trouble replicating this. Do you have a link I can look at to see this in action?

**Comment by katknow** [comment]
@kimisgold sure! Here it is: [https://katknowtesting.omeka-staging.net/items/show/491]. Just tried it again and it's still doing it for me (works on Safari, but nowhere else). I tried it on Mac & PC versions of the browsers and have the same issue on both computers...but it very well may be operator error on my part!

**Comment by katknow** [comment]
@kimisgold  this seems to be working on the front end across Chrome, Safari, Firefox, and Edge now. English is still the only option on the back end, but I don't know how much that matters.

**Comment by kimisgold** [comment]
Looked into it, and it was a case where the admin really wants the "Type" to be "subtitles", all lowercase. I believe that's more an issue with the Html5Media plugin and now with the theme, so we should be all good here.
