### ISSUE TITLE
Test featured content slider with pause/play button

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-bigpicture#33]
Currently, when the slider is playing, screen readers announce new slides as they appear regardless of where focus currently sits. This can be disruptive, so I've included a pause/play button for the slider. Test the following:

* The pause/play button controls the animation as expected when clicked.
* With a screen reader on, the user can navigate to the pause/play button via keyboard. The button should keep focus when activated. 
* Navigating further on the page, a paused slider does not disrupt the screen reader experience.

Test across desktop browsers.

**Comment by katknow** [comment]
The pause/play button works as described across browsers. However, my one concern is that if you can't see the screen and are tabbing to navigate the page depending on how fast you go you might get stuck an a loop with the featured items if they have long titles. I timed it and it takes approximately 4.5 seconds for the next slide, but if the title is more than a few words it doesn't finish and then by the time you tab again it starts reading another. If it's a short title, you can fairly easily tab to the pause/play. I don't know how big of a deal this is and whether it's worth fixing since it is technically functional, but I think it could be fixed by just slowing down how quickly the slides pass by.

**Comment by kimisgold** [comment]
Hmm, how would you feel about moving the pause/play button earlier in the tab order? That way we wouldn't be reliant on the variable length of slide titles.

**Comment by katknow** [comment]
I think that would be a good solution.

**Comment by kimisgold** [comment]
Okay, the slider controls are now earlier in the tab order. There is now also a theme setting to allow users to control the speed of the slides. Screen readers will also read a status message when the user has stopped or started the carousel. After activating the pause/play button, focus goes to an offscreen status message, as sighted users don't need it. Users will need to tab one more time to activate the toggle button, so this is expected behavior.

Please test these additional features with Voiceover and one of the other screen readers if possible.

**Comment by katknow** [comment]
This works well for me using both a Voiceover and Narrator.
